name: CI

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
      - feature/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: 21

      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dnet.bytebuddy.experimental=true

      - name: Test with Maven
        run: mvn -B test --file pom.xml -Dnet.bytebuddy.experimental=true