# Label pull requests based on the files that are modified.
name: Labeler

on:
  pull_request_target:
    branches:
      - main

jobs:
  label:
    if: ${{ false }} # This line deactivates the workflow temporarily
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'